### ISSUE TITLE
Jar size and MC 1.17.

### ISSUE THREAD

**Issue by K0-RR** [CodeeToasty/ColoredWaterMC#2]
You should update the Gradle to 7.0.1 to be able to build with Java 16, which is needed for MC 1.17.
Compress assets. You can use lossless compression to cut ~25% of the file size or go with lossy and make it 1/4 of the original size (the quality difference shouldn't be noticeable even when you use rough compression on the particles/splashes).

There is a GitHub bot that should do this for you https://imgbot.net/

**Comment by K0-RR** [comment]
Tried using lossy on yellow_splash_1.png - 8,0 KiB >> 105 B so like 99% smaller file size. So even if you do this only for splashes you should easily cut in half the jar size.

**Comment by CodeeToasty** [comment]
Updated to 1.17.
Had to temporarly remove colored lighting support since the mod that allows that isn't on 1.17 yet, will be re-added when possibile :)
I will reduce size as soon as i have time!
